# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# find_suitable_land.py
# Created on: 2019-04-02 11:27:58.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
US_Cities = "F:\\Demidov\\PythEveryone\\Lesson1\\us_cities.shp"
Buffered_cities = "F:\\Demidov\\PythEveryone\\Lesson1\\USA.gdb\\us_cities_buffer"
US_Roads = "F:\\Demidov\\PythEveryone\\Lesson1\\us_roads.shp"
Buffered_roads = "F:\\Demidov\\PythEveryone\\Lesson1\\USA.gdb\\us_roads_Buffer"
Intersected_buffers = "F:\\Demidov\\PythEveryone\\Lesson1\\USA.gdb\\us_cities_buffer_Intersect"
US_Boundaries = "us_boundaries"
Suitable_Land = "F:\\Demidov\\PythEveryone\\Lesson1\\USA.gdb\\suitable_land"

# Process: Buffer the cities
arcpy.Buffer_analysis(US_Cities, Buffered_cities, "10 Miles", "FULL", "ROUND", "ALL", "", "PLANAR")

# Process: Buffer the roads
arcpy.Buffer_analysis(US_Roads, Buffered_roads, "10 Miles", "FULL", "ROUND", "ALL", "", "PLANAR")

# Process: Intersect
arcpy.Intersect_analysis("F:\\Demidov\\PythEveryone\\Lesson1\\USA.gdb\\us_cities_buffer #;F:\\Demidov\\PythEveryone\\Lesson1\\USA.gdb\\us_roads_Buffer #", Intersected_buffers, "ALL", "", "INPUT")

# Process: Clip
arcpy.Clip_analysis(Intersected_buffers, US_Boundaries, Suitable_Land, "")

