# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# find_suitable_land_without_parametrs.py
# Created on: 2019-04-02 11:28:34.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: find_suitable_land_without_parametrs <Cities> <Cities_buffer_distance> <Roads> <Road_buffer_distance> <Boundaries> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Cities = arcpy.GetParameterAsText(0)

Cities_buffer_distance = arcpy.GetParameterAsText(1)
if Cities_buffer_distance == '#' or not Cities_buffer_distance:
    Cities_buffer_distance = "10 Miles" # provide a default value if unspecified

Roads = arcpy.GetParameterAsText(2)

Road_buffer_distance = arcpy.GetParameterAsText(3)
if Road_buffer_distance == '#' or not Road_buffer_distance:
    Road_buffer_distance = "10 Miles" # provide a default value if unspecified

Boundaries = arcpy.GetParameterAsText(4)

# Local variables:
Buffered_cities = "F:\\Demidov\\PythEveryone\\Lesson1\\USA.gdb\\us_cities_buffer"
Buffered_roads = "F:\\Demidov\\PythEveryone\\Lesson1\\USA.gdb\\us_roads_Buffer"
Intersected_buffers = "F:\\Demidov\\PythEveryone\\Lesson1\\USA.gdb\\cities_buffer_Intersect"
Suitable_Land = "F:\\Demidov\\PythEveryone\\Lesson1\\USA.gdb\\suitable_land"

# Process: Buffer the cities
arcpy.Buffer_analysis(Cities, Buffered_cities, Cities_buffer_distance, "FULL", "ROUND", "ALL", "", "PLANAR")

# Process: Buffer the roads
arcpy.Buffer_analysis(Roads, Buffered_roads, Road_buffer_distance, "FULL", "ROUND", "ALL", "", "PLANAR")

# Process: Intersect
arcpy.Intersect_analysis("F:\\Demidov\\PythEveryone\\Lesson1\\USA.gdb\\us_cities_buffer #;F:\\Demidov\\PythEveryone\\Lesson1\\USA.gdb\\us_roads_Buffer #", Intersected_buffers, "ALL", "", "INPUT")

# Process: Clip
arcpy.Clip_analysis(Intersected_buffers, Boundaries, Suitable_Land, "")

