# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# test.py
# Created on: 2019-05-01 00:34:02.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
arcpy.env.overwriteOutput = True
Precipitation = arcpy.GetParameterAsText(0)
Nebraska2= arcpy.GetParameterAsText(1)
NebrascaPrecipZones = arcpy.GetParameterAsText(2)

# Local variables:
#Precip2008Readings = r"F:\\Demidov\\PythEveryone\\PyCharmProject\\Lesson1\\Precip2008\\Precip2008.gdb\\Precip2008Readings"
idw_precipitation = "F:\\Demidov\\PythEveryone\\PyCharmProject\\Lesson1\\USA.gdb\\idw_precipitation"
reclassIdw = "F:\\Demidov\\PythEveryone\\PyCharmProject\\Lesson1\\Precip2008\\Precip2008.gdb\\reclassIdw"
RasterT_Reclass1 = "F:\\Demidov\\PythEveryone\\PyCharmProject\\Lesson1\\Precip2008\\Precip2008.gdb\\RasterT_Reclass1.shp"
#Nebraska = r"F:\Demidov\PythEveryone\PyCharmProject\Lesson1\Precip2008\Precip2008.gdb\Nebraska"
#NebraskaPrecipZones = "F:\\Demidov\\PythEveryone\\PyCharmProject\\Lesson1\\Precip2008\\Precip2008.gdb\\NebraskaPrecipZones"

# Process: IDW
arcpy.gp.Idw_sa(Precipitation, "ID", idw_precipitation, "1850,46467", "2", "VARIABLE 12", "")

# Process: Reclassify
arcpy.gp.Reclassify_sa(idw_precipitation, "VALUE", "27715,960938 57484,319210 1;57484,319210 80383,056342 2;80383,056342 111132,789063 3", reclassIdw, "DATA")

# Process: Raster to Polygon
arcpy.RasterToPolygon_conversion(reclassIdw, RasterT_Reclass1, "SIMPLIFY", "VALUE")

# Process: Clip
arcpy.Clip_analysis(RasterT_Reclass1, Nebraska2, NebrascaPrecipZones, "")

