# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# test.py
# Created on: 2019-05-01 00:34:02.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Precip2008Readings = "F:\\Demidov\\PythEveryone\\PyCharmProject\\Lesson1\\Precip2008\\Precip2008.gdb\\Precip2008Readings"
Idw_Precip201 = "F:\\Demidov\\PythEveryone\\PyCharmProject\\Lesson1\\USA.gdb\\Idw_Precip201"
Reclass_Idw_2 = "F:\\Demidov\\PythEveryone\\PyCharmProject\\Lesson1\\Precip2008\\Precip2008.gdb\\Reclass_Idw_2"
RasterT_Reclass1 = "F:\\Demidov\\PythEveryone\\PyCharmProject\\Lesson1\\Precip2008\\Precip2008.gdb\\RasterT_Reclass1.shp"
Nebraska = "Nebraska"
RasterT_Reclass1_Clip = "F:\\Demidov\\PythEveryone\\PyCharmProject\\Lesson1\\Precip2008\\Precip2008.gdb\\RasterT_Reclass1_Clip"

# Process: IDW
arcpy.gp.Idw_sa(Precip2008Readings, "ID", Idw_Precip201, "1850,46467", "2", "VARIABLE 12", "")

# Process: Reclassify
arcpy.gp.Reclassify_sa(Idw_Precip201, "VALUE", "27715,960938 57484,319210 1;57484,319210 80383,056342 2;80383,056342 111132,789063 3", Reclass_Idw_2, "DATA")

# Process: Raster to Polygon
arcpy.RasterToPolygon_conversion(Reclass_Idw_2, RasterT_Reclass1, "SIMPLIFY", "VALUE")

# Process: Clip
arcpy.Clip_analysis(RasterT_Reclass1, Nebraska, RasterT_Reclass1_Clip, "")

